language: ruby
rvm:
- 2.2.7
sudo: false
script: bundle exec rake deploy
env:
  global:
    secure: DJMJbZCidkw5YIbFLoQ+Kqk6Zqp+YV2J1pHcXojjJUQYj1ZyG8U/rK9F7vFjjjRj4qy0+yiT6NknKEv3lnibC98YoZUJStXS7TZI2n7qFArI6mrsnPE5S6A/nIsEGWB0GB3j/7fmjKsuMzBiHUmhB+Sd7gsdTOHMSyZPMN9FRS1BFE8X+fhcmglwArqcWaDvv4VhMym87OU4FMA3irqM35Mu+8bgy00wJMn1/xbj8f5NKlq9OZucQ1tffL2uPxu1GtNQ9kN68h8uFIjsDOIWV23Ej/YbpDw3dibMX1iE5vunwZn1GYHW7RsEYkzynGSCE/mprxu2fEWPSYk1/0Pvso3U6U5YdDiZWWCcmB5IVnjIx0OLRslnHEkgUEuThrNCGhuH14+X1/uhP3rk1kYAtJOEBT+X6b2ctNMUj1CYqddGwNkIMsWRK5x3xIlU/HufUQyhsNfnfgbX/f7qLWt8p5REhfC6GsYvN2AyPqzVC/ilw9YbfkAQrx2E6dMDU2RhEindALf6nJn1SyT49u5v23sRyoTT/RVrbwTzgkgX3ddiMS0Ycwt5ytF8A1Di1mIriILnzTdr9x01yiifieRhlst+vZdO7Lyezrniut36hfdYDcRciwLcLgRKwyTn6fec6D/aByvoEF+BpuOW/i8Z/3ZlVFMT8tz14/8qnmPj+5o=
